import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { Clock3, Mail, MapPin, Phone } from 'lucide-react'

const fallback = { phone: '+91 98765 43210', email: 'support@chalakgo.in', address: 'Virasat Homes, Narayan Vihar, Jaipur, Rajasthan, India', facebook: '', instagram: '', linkedin: '', youtube: '' }
const socialNetworks = [['Facebook', 'facebook'], ['Instagram', 'instagram'], ['LinkedIn', 'linkedin'], ['YouTube', 'youtube']]

export default function Contact() {
  const [settings, setSettings] = useState(fallback), [form, setForm] = useState({ name: '', phone: '', email: '', message: '' }), [notice, setNotice] = useState(''), [sending, setSending] = useState(false)
  useEffect(() => { fetch('https://chalakgo.onrender.com/api/settings').then(r => r.ok ? r.json() : null).then(x => x && setSettings(value => ({ ...fallback, ...value, ...x }))).catch(() => {}) }, [])
  const social = socialNetworks.filter(([, key]) => settings[key])
  const submit = async e => { e.preventDefault(); setSending(true); setNotice(''); try { const r = await fetch('https://chalakgo.onrender.com/api/contacts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) throw Error(d.message); setForm({ name: '', phone: '', email: '', message: '' }); setNotice('Thank you. We will contact you shortly.') } catch (x) { setNotice(x.message || 'Message could not be sent.') } finally { setSending(false) } }

  return <main className="min-h-screen bg-[#f7f9fc] px-5 py-16 text-[#101a31] sm:py-24"><section className="mx-auto max-w-[1240px]">
    <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} className="mx-auto max-w-2xl text-center"><p className="font-bold text-blue-600">CONTACT CHALAKGO</p><h1 className="mt-3 text-4xl font-extrabold sm:text-6xl">Let's make every journey smoother.</h1><p className="mt-5 text-lg leading-7 text-slate-600">Speak to our booking support team for instant rides, monthly driver plans, airport transfers, or city availability.</p></motion.div>
    <div className="mx-auto mt-12 grid max-w-[920px] gap-3 md:grid-cols-4">
      <InfoCard icon={<Phone size={25} />} tone="bg-blue-600" title="Call Us" text={settings.phone} href={`tel:${settings.phone.replace(/\s/g, '')}`} />
      <InfoCard icon={<Mail size={25} />} tone="bg-violet-600" title="Email" text={settings.email} href={`mailto:${settings.email}`} />
      <InfoCard icon={<MapPin size={25} />} tone="bg-rose-500" title="Office" text={settings.address} />
      <InfoCard icon={<Clock3 size={25} />} tone="bg-emerald-600" title="Working Hours" text="24/7 booking assistance" />
    </div>
    {social.length > 0 && <div className="mt-8 flex flex-col items-center gap-3"><p className="text-sm font-bold text-slate-500">Follow ChalakGo</p><div className="flex flex-wrap justify-center gap-3">{social.map(([name, key]) => <a key={key} href={settings[key]} target="_blank" rel="noreferrer" aria-label={name} className="grid h-11 w-11 place-items-center rounded-full bg-[#0b1c38] text-white shadow-md transition hover:-translate-y-1 hover:bg-blue-600"><SocialIcon name={name} /></a>)}</div></div>}
    <div className="mt-12 grid gap-7 lg:grid-cols-2"><div className="rounded-3xl bg-white p-7 shadow-xl sm:p-9"><p className="text-sm font-bold text-blue-600">SEND A MESSAGE</p><h2 className="mt-2 text-3xl font-extrabold">How can we help?</h2><form onSubmit={submit} className="mt-7 grid gap-4 sm:grid-cols-2"><Input placeholder="Your name" value={form.name} set={v => setForm({ ...form, name: v })} /><Input placeholder="Mobile number" type="tel" value={form.phone} set={v => setForm({ ...form, phone: v })} /><Input wide placeholder="Email address" type="email" value={form.email} set={v => setForm({ ...form, email: v })} /><textarea required className="input min-h-28 py-3 sm:col-span-2" placeholder="How can we help?" value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} /><button disabled={sending} className="rounded-xl bg-blue-600 py-4 font-bold text-white shadow-lg shadow-blue-200 disabled:opacity-60 sm:col-span-2">{sending ? 'Sending...' : 'Send Message'}</button></form>{notice && <p className="mt-4 text-center font-medium text-blue-700">{notice}</p>}</div>
      <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><div className="p-7 pb-5 sm:px-9 sm:pt-9"><p className="text-sm font-bold text-blue-600">FIND US IN JAIPUR</p><h2 className="mt-2 text-3xl font-extrabold">Visit our office</h2><p className="mt-2 text-sm text-slate-500">{settings.address}</p></div><iframe title="ChalakGo Jaipur location" src="https://www.google.com/maps?q=Jaipur%2C%20Rajasthan&z=12&output=embed" className="h-[320px] w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div>
    </div>
  </section></main>
}

function InfoCard({ icon, tone, title, text, href }) { const content = <><span className={`grid h-11 w-11 place-items-center rounded-xl ${tone} text-white shadow-lg`}>{icon}</span><h2 className="mt-4 text-lg font-extrabold">{title}</h2><p className="mt-2 text-sm leading-5 text-slate-500">{text}</p></>; return href ? <a href={href} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg">{content}</a> : <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">{content}</article> }
function Input({ placeholder, type = 'text', value, set, wide }) { return <input required type={type} className={`input ${wide ? 'sm:col-span-2' : ''}`} placeholder={placeholder} value={value} onChange={e => set(e.target.value)} /> }
function SocialIcon({ name }) { if (name === 'Facebook') return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5 fill-current"><path d="M13.8 21v-8h2.7l.4-3.1h-3.1v-2c0-.9.3-1.5 1.6-1.5H17V3.6c-.3 0-1.2-.1-2.3-.1-2.3 0-3.9 1.4-3.9 4v2.4H8.2V13h2.6v8h3Z" /></svg>; if (name === 'Instagram') return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5 fill-none stroke-current stroke-[2]"><rect x="3" y="3" width="18" height="18" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.4" cy="6.7" r=".8" className="fill-current stroke-none" /></svg>; if (name === 'LinkedIn') return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5 fill-current"><path d="M5.1 8.2A1.9 1.9 0 1 0 5.1 4.4a1.9 1.9 0 0 0 0 3.8ZM3.5 9.7h3.2V20H3.5V9.7Zm5.2 0h3.1v1.4h.1c.4-.8 1.5-1.8 3.2-1.8 3.4 0 4 2.2 4 5.2V20h-3.2v-4.9c0-1.2 0-2.7-1.7-2.7s-2 1.3-2 2.6V20H8.8V9.7Z" /></svg>; return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5 fill-current"><path d="M21.6 7.2a3 3 0 0 0-2.1-2.1C17.6 4.6 12 4.6 12 4.6s-5.6 0-7.5.5A3 3 0 0 0 2.4 7.2C1.9 9.1 1.9 12 1.9 12s0 2.9.5 4.8a3 3 0 0 0 2.1 2.1c1.9.5 7.5.5 7.5.5s5.6 0 7.5-.5a3 3 0 0 0 2.1-2.1c.5-1.9.5-4.8.5-4.8s0-2.9-.5-4.8ZM10 15.4V8.6l5.7 3.4-5.7 3.4Z" /></svg> }
